# Generated by Django 4.1 on 2022-09-21 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywatchlist",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mywatchlist",
            name="release_date",
            field=models.DateField(),
        ),
    ]
