# Generated by Django 4.1 on 2022-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0002_alter_mywatchlist_rating_and_more"),
    ]

    operations = [
    ]
